// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: commons/error/v1/error.proto

package commonserr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse_ErrorCode int32

const (
	ErrorResponse_ERROR_CODE_UNSPECIFIED ErrorResponse_ErrorCode = 0
)

// Enum value maps for ErrorResponse_ErrorCode.
var (
	ErrorResponse_ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
	}
	ErrorResponse_ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
	}
)

func (x ErrorResponse_ErrorCode) Enum() *ErrorResponse_ErrorCode {
	p := new(ErrorResponse_ErrorCode)
	*p = x
	return p
}

func (x ErrorResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_error_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_commons_error_v1_error_proto_enumTypes[0]
}

func (x ErrorResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResponse_ErrorCode.Descriptor instead.
func (ErrorResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_commons_error_v1_error_proto_rawDescGZIP(), []int{0, 0}
}

// Data returned in the Error Details.
type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An enum value that indicates which error occurred.
	ErrorCode ErrorResponse_ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=commons.error.v1.ErrorResponse_ErrorCode" json:"error_code,omitempty"`
	// A field containing extra details about the error.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commons_error_v1_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commons_error_v1_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_commons_error_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetErrorCode() ErrorResponse_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorResponse_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_commons_error_v1_error_proto protoreflect.FileDescriptor

var file_commons_error_v1_error_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42,
	0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75,
	0x72, 0x70, 0x6f, 0x73, 0x65, 0x69, 0x6e, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commons_error_v1_error_proto_rawDescOnce sync.Once
	file_commons_error_v1_error_proto_rawDescData = file_commons_error_v1_error_proto_rawDesc
)

func file_commons_error_v1_error_proto_rawDescGZIP() []byte {
	file_commons_error_v1_error_proto_rawDescOnce.Do(func() {
		file_commons_error_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_commons_error_v1_error_proto_rawDescData)
	})
	return file_commons_error_v1_error_proto_rawDescData
}

var file_commons_error_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commons_error_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commons_error_v1_error_proto_goTypes = []interface{}{
	(ErrorResponse_ErrorCode)(0), // 0: commons.error.v1.ErrorResponse.ErrorCode
	(*ErrorResponse)(nil),        // 1: commons.error.v1.ErrorResponse
}
var file_commons_error_v1_error_proto_depIdxs = []int32{
	0, // 0: commons.error.v1.ErrorResponse.error_code:type_name -> commons.error.v1.ErrorResponse.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commons_error_v1_error_proto_init() }
func file_commons_error_v1_error_proto_init() {
	if File_commons_error_v1_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commons_error_v1_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commons_error_v1_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_error_v1_error_proto_goTypes,
		DependencyIndexes: file_commons_error_v1_error_proto_depIdxs,
		EnumInfos:         file_commons_error_v1_error_proto_enumTypes,
		MessageInfos:      file_commons_error_v1_error_proto_msgTypes,
	}.Build()
	File_commons_error_v1_error_proto = out.File
	file_commons_error_v1_error_proto_rawDesc = nil
	file_commons_error_v1_error_proto_goTypes = nil
	file_commons_error_v1_error_proto_depIdxs = nil
}
