// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: commons/error/v1/error.proto

package commonserr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data returned in the Error Details.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application error code
	ErrorCode string `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// A field containing extra details about the error.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_commons_error_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commons_error_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_commons_error_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_commons_error_v1_error_proto protoreflect.FileDescriptor

const file_commons_error_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1ccommons/error/v1/error.proto\x12\x10commons.error.v1\"H\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBNZLgithub.com/purposeinplay/go-commons/errors/proto/commons/error/v1;commonserrb\x06proto3"

var (
	file_commons_error_v1_error_proto_rawDescOnce sync.Once
	file_commons_error_v1_error_proto_rawDescData []byte
)

func file_commons_error_v1_error_proto_rawDescGZIP() []byte {
	file_commons_error_v1_error_proto_rawDescOnce.Do(func() {
		file_commons_error_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_error_v1_error_proto_rawDesc), len(file_commons_error_v1_error_proto_rawDesc)))
	})
	return file_commons_error_v1_error_proto_rawDescData
}

var file_commons_error_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commons_error_v1_error_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: commons.error.v1.ErrorResponse
}
var file_commons_error_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commons_error_v1_error_proto_init() }
func file_commons_error_v1_error_proto_init() {
	if File_commons_error_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_error_v1_error_proto_rawDesc), len(file_commons_error_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_error_v1_error_proto_goTypes,
		DependencyIndexes: file_commons_error_v1_error_proto_depIdxs,
		MessageInfos:      file_commons_error_v1_error_proto_msgTypes,
	}.Build()
	File_commons_error_v1_error_proto = out.File
	file_commons_error_v1_error_proto_goTypes = nil
	file_commons_error_v1_error_proto_depIdxs = nil
}
