name: lint-test-blockingqueue

on:
  push:
    branches:
      - main
    paths:
      - blockingqueue/**

env:
  PACKAGE: blockingqueue
  GO_VERSION: 1.19

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m -c=$GITHUB_WORKSPACE/.golangci.yml
          working-directory: ./${{ env.PACKAGE }}/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test
        run: make test -C $GITHUB_WORKSPACE/${{ env.PACKAGE }}