// Package smartbear provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package smartbear

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorDetail An object to provide explicit details on a problem towards an API consumer.
type ErrorDetail struct {
	// Code A string containing additional provider specific codes to identify the error context.
	Code *string `json:"code,omitempty"`

	// Detail A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`

	// Header The name of the header that is the source of error.
	Header *string `json:"header,omitempty"`

	// Parameter The name of the query or path parameter that is the source of error.
	Parameter *string `json:"parameter,omitempty"`

	// Pointer A JSON Pointer to a specific request body property that is the source of error.
	Pointer *string `json:"pointer,omitempty"`
}

// Errors An array of error details to accompany a problem details response.
type Errors = []ErrorDetail

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Code An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors An array of error details to accompany a problem details response.
	Errors *Errors `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// BusinessRuleViolation defines model for BusinessRuleViolation.
type BusinessRuleViolation = ProblemDetails

// Forbidden defines model for Forbidden.
type Forbidden = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// ResourceAlreadyExists defines model for ResourceAlreadyExists.
type ResourceAlreadyExists = ProblemDetails

// ServerError defines model for ServerError.
type ServerError = ProblemDetails

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ProblemDetails

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9w762/btrf/yoHu/bDi2ombptvib2maYr3YuiBpOwxtAdPikc2VIlWSSuIV+d8v+NDT",
	"kuPnbfDblzUWdd7n8Lz0PYplmkmBwuho/D3Ce5JmHN2/p7lmArUeqpzj8JZJTgyTwj6iqGPFMv9ndI2Z",
	"Qo3CuOcgEyBwenICrwiFa/yWozagUGdSaIS7OSoEM0dQ4RHTQBFTpMDELeGMAtHAEkgI4xqMhBTRQIzK",
	"ECagoAosVYD3GcYerz6KBtEt4TlaCmNJMRpHpycnw9HzaBBRNITxaBy9r2GeSrqw6Eu8goKQxiFkYtbE",
	"5eCjUlLpaPzpewXxD3LP0jyFbzkRhpkFEM7lnWMHzs7OokGUSSYMqmgcHReHoodBDcRfCFQ61DJJUMFE",
	"4L0ZUrKYAEXOblEtrCCEFMPLD0AoVag16iZoPWdZxsTs3D8+jmUujDokpj+9BTx8GUTaEJPraHx6cjKI",
	"DDPcSv9VIb9rq6uPpQUNIrPI7IG5MZkeHx9nSk45pnqocMa0UYsjnRJlpkjUUSzT4z5TfHgYRIlUU0Yp",
	"OsMs9d/St5a5ihFimXOv4qn91eRKoDO3mj1KZU3CniG5mUvF/kUa1RgcvagYfFPiLlkiU5mb8ZQT8dWR",
	"F2xraG1tmCmZoTKLYSJVSsyarjQarXIl4s24AA1Uoief4y0qMvPOFkulMDYQEHd4ymg0HJ2u9JRYCuuC",
	"GgikhFtISEu8Rw0ZjSoZvQ3O9cqCuCqofFPQsaElrBTnY/Ie3jEzHxY+/J8l+87IlGtn6QQyqZlhtwjW",
	"h2eo+oLSl6esxJpz76g3s0K8xWVQKtWj7dHaL2tqTZRwmxbjgG7oOx8DQXuRuufqEaHv3XGeoAK6HOjc",
	"P4bJO+vPE3sxVICO4Ioj0Whh3TKKMEmlMHO+mIBUMPmWE2VQ8cWk4Wz/dZwS9dXlFxcyTXPBYie248QR",
	"LuKNvfDA5hDkOZwjoaj2eXMVmvKQCzFSuCO6CnJ9ev+5T++dkbKNiiiSokH1qOcVpP/mX9w14nUL81Fx",
	"H+Di+pbbVE9aWZh5JRBr4qXYjg4v/C6vqwMM77RNwv9sPTSOMTOPu8wP02PJ7X5zvp3U93Ij9XlUm7vM",
	"VUnUvqS9JMt1BP7UfGdn4fe5jK+FkYI2ylavDrsGohDOby4sua9vLuxdVACLxpGWagPn+eEaPUwG2JF7",
	"9Gm4zBY6VfvrxrlIcaADw4Ya2TEL6JP1Gvo4aHL4NHXT54IhWzQyG1J5JyZlJwE8SOtuS/DgEeednN9c",
	"+JTy9c3FZE8OfEBz4SxGoXEYExEj50jXM4qXoxdwg+qWxQgfBLkljJMpx4ZxCGcbAQEQrWXMiJWaNUFf",
	"a3OGwsCcaJgiCiiJADPPNSgUFJ2A7WEd0OUVuob9NHRbHGa6fr5oHvXRtJC5KoiSCqSaEcH+9WwvE1mW",
	"FM4eY+NfJ7Fr5UFKBJmhBQKqJsDbRrh4We9P/R6ouihVsbHGl7VZ1zHeZ0z9MA0H7E9UtYG6Q+n0Moh+",
	"a40WurP6TJnWTMyaxeCesiX1LXdamljgk6rytjm9TJmxAp0uQqdM6Dz1aU5nFD/ri+I29fI82BBeRtNG",
	"rd97q/4R3myc3lyw3ULsFe8BEtMnJeq+S7LZf/kuSIoPFqiF7xym2Zy0z/tvuP831TUrvj3pa+KhTWo5",
	"wTaqOtlQVb+9f3/VqrAf9Y3m8e0l3JJjv4gP4B5PS9x9/hFaHt99a6PhGpt0Pn6A4mqJ6X705VJ9n/va",
	"ZH9Xxb3YUHE9lcbavlLJY2epV6BWCv4QTvN0ldDnQa2mSd8dUyuj1rtkDq5XIc0wkbmgq2bZ7kXXVg1T",
	"basFW2X6N+s8nFY8vKsd6BlVFwCHhCskdDHEe6bN2nZ0ttqOCsOwajBq4RJ1CbFCYlzqUnBj5sRAoAAC",
	"BV2mdNa52BGATNHC98BpC1rTfc8qEZ23kW6o25bYrEhtZYHKO2S/Tv0pQOFqArQZHBGQi9IH/Pv1gqBm",
	"nTf+7ctwpke5ocYZ1gqc1QSFgijOlUJh+KJeGq0ipVXd9VOUi9qCRScp9orTGoz8isJZuEZXapUDuB6H",
	"6FzzaGj9eUXzB9HY8+gh1iF05l4ps+kU7+dMQzARkHGcK10VtMu7TrnIlLTsudL0s/gs3lfFLdM6t0ZQ",
	"vuecIiGMI4WKlCO4CFtR1W/A2VQRxVAHziHNuWHhTnArTjERQTZINOMuUmq3r2QkUKZjhWjACkJbEdfY",
	"sr8NgCSJVNTV3eXwU1UFOpkyzoxbI9K5SkiMQDivk1ijReDM+r99TyBSSKQCAkYxwt1zdxTupPqacHkH",
	"UvjyWTNqhda38bUqQyuMp+f++NuCL46X+xyhP1jq0lVZrRqmq2wZtByr1bKsw0+kSq3MTL0bWK6MlGlf",
	"huYt7V+5+lhJuRUQ1o1iS5b+EO4GF87dbfCK0BDmveCFQeH+SbKMF/PsgOd//tF+Z7C+Whh08ErSRTHG",
	"flNOx/5bYeIG5dVq4nHx8iOrI4N+yH8xM78s86KtcTQSrG58HwuL3AJJ6KL2w92ZjeWWfYUtKNXPSDdU",
	"SM9EdBXsLXh5fDq+hLHseW/J0PKI6hEMO7C1cnbZj3czi+vt3a+Gvxe2Oq0v5MR1W38URU/DphPYBpQ/",
	"3qirUDQsem3I7TK6G9wWJK/oniwhuaoX6htBr9UrvUB3IL67kHX5azzHlPQB9E/18ZW/dF67O1f7q6ud",
	"plXZQGOrxCaWjcQx5GdIj8CmZ5eBZlvuTGqVzqTMjvxNX1Y+emxfgyF86mxSfvlpp+bk8TMP+23nVpsP",
	"H+ujWHXlrcbkPHpXRA5Igae7cbW5uJoO0eaitWC0rcA6L6Q+Tkrr3p6ZEsTxMyj+62asyjJ35a19K/WJ",
	"sjXY3gfC0jBsuCk+J7jOOX6sf46yRQY67YO1Mlyt+g7hEAGq+9MY0/o0ZtUnMQ+D2kcK24mq8YHFSvFU",
	"Jw8kkK5vM6wYMlS+fLLFqo0poTFVFGy+L+Ck8U6aN0WHbQthiNrrK2VRtfIOJIveDqBj8zo8Cj2ty7KT",
	"twXPpA1jJeN9XcT9i6Gz18e0l4I1i0bfr7AG32xzQvKds8uin7OFaHQTwkrBNHqB+5bGmi3EwDSL8UOz",
	"D7gF72GP4KK+5rNSAB2rJOUmyWW1SLIWjHJ5oexsthh6VBXtZughNMLiurs210ss6R9aLdAttNDuoq7k",
	"u3F4nww3OrUhRLeatZbfqju1i9PdLkNZyXVHR2t/nP9d2wJat21bI8Ax5Nh4HfqE7b7yuQA5/Qdj4y66",
	"8KkJ3ltRMRNqDm2DG6natPKOKOqWGc+v3jZGciHlZqirnukSxmIJMXQ93USOUmYfE151fHWGMUtYDBaM",
	"S0cYRWFY4ieBvnXr9HtvLO6U3P+OYmbm0fjlqOxLelzRQ9WxXaZnpojIOVFQe1DG84IKj08hd/eADf/N",
	"UmXQngsOWu1YPQAi6LFUtSF9jebT0dnPHVT3LYTYGCBIirZeNNVY35kE85tl4QKTiae9he/56OS0A9+K",
	"IXsbZd+m7O40FH3uZVX9782f7+DKP/dKKBXU2LgtC8gdiXG96bAdMf5U2NCX8pz3HUv0Zc9U/FwAUYos",
	"SrSlU1nyYxsViFjU3Kt4XBT6lkxmMNWPRZO6nz841t76156PRpVDOGLs81bwGX9fz3u907fcwp4Fwmix",
	"H1k6sUGSQi4oKm2IoDXPnRKNNHgZUyDvBGTSxmpGOBhyL4VMF35xMVR1O/n4PE+JGNqEzS1f2ghHhM/j",
	"S17ceMSm+LEfS8alqQfdrOeyuLI51dBWaLta2cSdofLD9VtQmKCnxhuzj4IMdTNA9VMNbw2kxAnT/s/e",
	"nguGnEKSKzNHe4n60ttKgyVAsURJ1/PYYljUFTLcfpI/4O1khsKWUNVSh1RsxkSRZCZSraGG4nOniAnz",
	"4sQTydI8jcYvz84GUcqE/+t5zfSLr5MfyoFWx900l8oM2uai8zQlatGiww0snXT1vGztxXMiZgiJkmmd",
	"AyP7+RkA3seYuU+4IctVJrVvBHIZEx6WftdThP9hGztq8FQXcK7Y5oHSy3c5TvoPPhLZbSqTZkyaFKlJ",
	"CCc6xEbXsKgs1g3T3VKPH/w67oKwKdBchZ0fl6wQzgHvMc79hPuzaA7WPb4wL9XFwPTT9ZuLs9OXv1Q9",
	"p7u7uyOVxEOkzEh1JNXs2JJ0rJLYHnwGP7m2r+IL9/Ivv45qLxspuT5iaBL34tyk3L5oDz17Vg7rAy1M",
	"A94bFLS+pZ5IzuWd5auK2WPXNptYF5vA0N6MPs0q9ewvTEY7IvQUjb1QuwK1h+pF6+AK2rrQdABW5HR4",
	"b3LCGyoqWiXSOgjJddsDPgv4LKDTBKpQ5MMF00BlSpiA3DDO/vXT/U83KVHmFRIFAYCG63BxrN8pfOaH",
	"/sW0u3VDDqJbVNpb6/Oj0dHIOpzMUJCMRePohfvJZlBmrqOxyDl/+L8AAAD//9xeSHcBRwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
